### ISSUE TITLE
Query regarding pipeline options (parameters)

### ISSUE THREAD

**Issue by wasimbt** [wslh-bio/spriggan#12]
Hi Spriggan team, 

Thank you for creating such an excellent pipeline, it helps alot! 

Could you please let me know, what are the different options (parameters) available at each analysis step and how can i test them on our dataset? Would be nice to have a detailed page of options (as well as the default) and their use case scenario. 

Many thanks!  
Wasim

**Comment by AbigailShockey** [comment]
Hi Wasim,

Thank you for this suggestion. We have now added a "Parameters" section to Spriggan's README which includes a description of its main parameters and their defaults.

**Comment by AbigailShockey** [comment]
This issue has been resolved in the 1.4.0 release (https://github.com/wslh-bio/spriggan/releases/tag/1.4.0)
